LaptopStore/Models/Laptop.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaptopStore.Models
{
    public class Laptop
    {

        public int Id { get; set; }

        public string ItemTitle { get; set; }

        public string Price { get; set; }
        public string Image { get; set; }
        public string ModelName { get; set; }
        public string RamSize { get; set; }
        public string ProcessorBrand { get; set; }
        public string ProcessorSpeed { get; set; }
        public string ProcessorType { get; set; }
        public string HardDiskSize { get; set; }
        public string HardDiskType { get; set; }
        public string Display { get; set; }
        public string Color { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string Battery { get; set; }
        public string Weight { get; set; }
        public List<Orders> Orders { get; set; }


    }
}

LaptopStore/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LaptopStore.Models
{
    public class Payment
    {
        
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Card Number")]
        public string CardNumber { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Expiry")]
        public string Expiry { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "CVV")]
        public string CVV { get; set; }
    }
}

LaptopStore/Controllers/LaptopController.cs
using LaptopStore.Models;
using LaptopStore.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaptopStore.Controllers
{
    public class LaptopController : Controller
    {
        ApplicationDBContext context;

        CustomerRepository customerRepo;
        ICrud<Laptop> laptopRepo;
        OrderRepository orderRepo;
        public LaptopController(CustomerRepository customers,ICrud<Laptop> laptops,OrderRepository orders)
        {
            customerRepo = customers;
            laptopRepo = laptops;
            orderRepo = orders;
            context = new ApplicationDBContext();
        }
        public IActionResult Index()
        {
            var curUser = HttpContext.Session.GetString("email");
            ViewBag.usr = curUser;
            var laptops = laptopRepo.GetAll();
            return View(laptops);
        }
        public IActionResult AddShippingDetails()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddShippingDetails(Customer c)
        {
            ModelState.Remove("Id");
            if (ModelState.IsValid)
            {
                context.Customers.Add(c);
                HttpContext.Session.SetString("email", c.Email);

                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Details(int id)
        {
            var laptop = laptopRepo.Get(id);
            return View(laptop);
        }

        public IActionResult Payment(int id)
        {
            bool isLoggedIn = ((User != null) && User.Identity.IsAuthenticated) ? true : false;
            if (isLoggedIn)
            {

                var laptop = laptopRepo.Get(id);
                string lid = laptop.Id.ToString();
                HttpContext.Session.SetString("laptopId", lid);
                return View();
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
        }
        [HttpPost]
        public IActionResult Payment(Payment p)
        {
            if (ModelState.IsValid)
            {
                string email = HttpContext.Session.GetString("email");
                int cid = customerRepo.GetCustIdByEmail(email);
                Customer cust = customerRepo.GetCustByEmail(email);
                int lid = int.Parse(HttpContext.Session.GetString("laptopId"));
                var laptop = laptopRepo.Get(lid);

                context.Database.ExecuteSqlRaw($"insert into Orders values ({cid},{lid})");
                //Orders ord = new Orders() { Laptops=laptop,Customers=cust,CustomerId=cid,LaptopId=lid };
                //orderRepo.Add(ord);
                return RedirectToAction("Confirmation");
            }
            else
            {
                HttpContext.Session.Clear();
            }
            return View();
        }

        public IActionResult Confirmation()
        {
            int lid = int.Parse(HttpContext.Session.GetString("laptopId"));
            var laptop = laptopRepo.Get(lid);
            return View(laptop);
        }

        public IActionResult CurrentOrders()
        {

            string email = HttpContext.Session.GetString("email");

            int id = customerRepo.GetCustIdByEmail(email);
            List<Orders> orders = orderRepo.GetByCustId(id);
            ViewBag.cnt = orders.Count;
            
            List<Laptop> laptops=new List<Laptop>();
            if (orders.Count == 0)
            {
                return View(laptops);
            }
            foreach (var item in orders)
            {
                int lid = item.LaptopId;
                Laptop lap = laptopRepo.Get(lid);
                laptops.Add(lap);
            }


            return View(laptops);
        }


    }
}

LaptopStore/Views/Laptop/AddShippingDetails.cshtml
@model LaptopStore.Models.Customer

@{
    ViewData["Title"] = "AddShippingDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add Shipping Details</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddShippingDetails">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="Id" class="control-label"></label>*@
                <input  type="hidden" asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaptopStore/Views/Laptop/Confirmation.cshtml
@model LaptopStore.Models.Laptop
@{
    ViewData["Title"] = "Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Confirmation</h1>
<h1>Order Confirmed</h1>
<h1>@Model.ItemTitle</h1>

LaptopStore/Views/Laptop/CurrentOrders.cshtml
@model IEnumerable<LaptopStore.Models.Laptop>
@{
    ViewData["Title"] = "CurrentOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int cnt = int.Parse(ViewBag.cnt.ToString());
    DateTime nw = DateTime.Now;
    Random ran = new Random();
}
<style>
    .card {
        height: 60vh;
        margin: 25px;
        padding: 25px;
    }

    .center img {
        text-decoration: none;
        color: inherit;
        border: none;
        outline: none;
        height: 162px;
        width: 250px;
        margin: 20px 0px;
    }

    .center {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        text-align: center;
    }

    img {
        height: 150px;
        width: 150px;
        border-radius: 50%;
    }

    .order-data {
        vertical-align: middle;
        align-items: center;
        align-self: center;
    }

    .card-table {
        margin-top: 25px;
        position: relative;
        display: flex;
        flex-direction: column;
        background-clip: border-box;
        border: 1px solid black;
        border-radius: .25rem;
    }
</style>

@if (cnt == 0) { 
<div class="container">
    <div class="card">
        <h5 class="card-title">My Orders</h5>

    </div>
    <div class="center">
        <img src="~/images/undraw_shopping_app_flsj.svg" alt="sompic">
        <h4>No active orders</h4>
        <a asp-action="Index">Shop now</a>
    </div>
</div>
}

else
{
    foreach (var item in Model)
    {


<div class="card" style="height: 16rem;">
    <h5 class="card-header">@item.ItemTitle</h5>
    <div class="card-body">
        <h5 class="card-title"><span class="badge bg-primary">@item.Price</span></h5>
        <p class="card-text"><span style="color:green;">Arriving by @nw.AddDays(ran.Next(5)).DayOfWeek</span></p>
        <a class="btn btn-primary" asp-controller="Laptop" asp-action="Details" asp-route-id="@item.Id">Details</a>
    </div>
</div>
    }

}

LaptopStore/Views/Laptop/Details.cshtml
@model LaptopStore.Models.Laptop
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="row-fluid">
                <div style="width:95%" id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="1500">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bGFwdG9wc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&w=1000&q=80" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://i.dell.com/is/image/DellContent//content/dam/global-asset-library/Products/Notebooks/Inspiron/15_5510_non-touch/in5510nt_cnb_00055lf110_gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=4426&hei=2820&qlt=100,0&resMode=sharp2&size=4426,2820" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://i.pcmag.com/imagery/roundups/02naaOkVLe7DIiejFUyDPJp-33..1605019187.jpg" class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            </div>
        <div class="col-md-6">
            <h3>@Model.ItemTitle</h3>
            <br />
            <div class="row">
                <div class="col-md-8">
                    <h5>@Model.Price</h5>
                    <h5 style="color:green;">In stock</h5>
                    @{
                        Random r = new Random();
                        int num = r.Next(5);
                        DayOfWeek wk = DateTime.Today.AddDays(num).DayOfWeek;
                    }
                    <h5>Get it by @wk</h5>
                </div>
                <div class="col-md-4">
                    <a asp-action="Payment" asp-route-id="@Model.Id" class="btn btn-block btn-success">Buy Now</a>
                </div>
            </div>


            
        </div>
        </div>
    <br />
    <h2>Product Description</h2>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Model Name</th>
                <td>@Model.ModelName</td>
            </tr>
            <tr>
                <th>Ram</th>
                <td>@Model.RamSize</td>
            </tr>
            <tr>
                <th>Processor Brand</th>
                <td>@Model.ProcessorBrand</td>
            </tr>
            <tr>
                <th>Processor Speed</th>
                <td>@Model.ProcessorSpeed</td>
            </tr>
            <tr>
                <th>Processor Type</th>
                <td>@Model.ProcessorType</td>
            </tr>
            <tr>
                <th>Storage Type</th>
                <td>@Model.HardDiskType</td>
            </tr>
            <tr>
                <th>Storage Size</th>
                <td>@Model.HardDiskSize</td>
            </tr>
            <tr>
                <th>Display</th>
                <td>@Model.Display</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>@Model.Color</td>
            </tr>
            <tr>
                <th>Height</th>
                <td>@Model.Height</td>
            </tr>
            <tr>
                <th>Width</th>
                <td>@Model.Width</td>
            </tr>
            <tr>
                <th>Storage Size</th>
                <td>@Model.HardDiskSize</td>
            </tr>
        </tbody>
    </table>


</div>

LaptopStore/Views/Laptop/Index.cshtml
@model IEnumerable<LaptopStore.Models.Laptop>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
<style>
    img {
        margin-bottom: 15px;
        transition: 0.3s ease-in-out;
    }


       img:hover {
            transition: 0.3s ease-in-out;
            transform: scale(1.1);
        }

    .carousel-inner img {
        margin: auto;
    }

  

    
</style>

<h4>@ViewBag.usr</h4>
<style>
    .img-fluid {
        max-width: 78%;
        height: 181 px;
    }
</style>
<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <img class="img-fluid" src=@item.Image height="auto" width="auto" />
        </div>
        <div class="col-md-8">
            <h3>@item.ItemTitle</h3>
            <br />
            <h4>
                <span class="badge badge-pill badge-success">  @item.Price</span>
              
            </h4>
            @{
                Random r = new Random();
                int num = r.Next(5);
                DayOfWeek wk = DateTime.Today.AddDays(num).DayOfWeek;

                }

        <div class="row">
            <div class="col-md-4">
                <h4>Get it by @wk</h4>

            </div>
            <div class="col-md-4">
                <a class="btn btn-primary btn-block" asp-controller="Laptop" asp-action="Details" asp-route-id="@item.Id">Details</a> 


            </div>

        </div>
            
            <hr  style="height:3px"/>
        </div>
        }
</div>

LaptopStore/Views/Laptop/Payment.cshtml
@model LaptopStore.Models.Payment

@{
    ViewData["Title"] = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<style>
    .card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }

</style>

<div class="card text-white bg-success mb-3" style="max-width: 18rem;">
    <div class="card-header">Payment <i class="fa fa-money-check-alt"></i></div>
    <div class="card-body">
     


        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-controller="Laptop" asp-action="Payment">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CardNumber" class="control-label"></label>
                        <input asp-for="CardNumber" class="form-control" />
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Expiry" class="control-label"></label>
                        <input asp-for="Expiry" class="form-control" />
                        <span asp-validation-for="Expiry" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CVV" class="control-label"></label>
                        <input asp-for="CVV" class="form-control" />
                        <span asp-validation-for="CVV" class="text-danger"></span>
                    </div>
                    <div class="form-group fmy">
                        @*<input type="submit" value="Pay" class="btn btn-primary" />*@
                        @*<a asp-controller="Laptop" asp-action="Payment" class="btn btn-primary btn-block">Pay</a>*@
                        <input type="submit" value="Pay" class="btn btn-primary btn-block" />

                    </div>
                </form>
            </div>
        </div>


    </div>
</div>